### PR TITLE
feat: add typeorm migrations to docker compose

### PR DESCRIPTION
**Pull request by k-ong**
- Load database configurations from the config file into typeorm configurations.
- Pass database configurations into the app from environment variables

### CODE REVIEW

**Comment by nad-au** [comment]
Thanks @k-ong tested working but thinking about dev experience, to run migrations you'd need to take down and restart containers? Also reverting migrations would be a problem. Still thinking this might be best tackled running TypeORM CLI outside the container?

**Comment by k-ong** [comment]
Running the app (main) is independent of the migrations container. As the migration container will stop at the end of the run, running the migrations can be done repeatedly:

```
$ docker-compose up  migration
postgres is up-to-date
Starting migration ... done
Attaching to migration
migration    | 
migration    | > nest-settings@0.0.1 typeorm /usr/src/app
migration    | > node --require ts-node/register ./node_modules/typeorm/cli.js "migration:run"
migration    | 
migration    | query: SELECT * FROM current_schema()
migration    | query: SHOW server_version;
migration    | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
migration    | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
migration    | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
migration    | No migrations are pending
migration exited with code 0
```

**Comment by k-ong** [comment]
However, totally agree that rolling back migrations will be challenging

**Comment by nad-au** [comment]
Closing for now as I've found a workaround to provide full TypeORM CLI support including reverts.

**Pull request closed without merging**
